# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Review.destroy_all
Beer.destroy_all
User.destroy_all
Country.destroy_all

users = User.create([
  {username: "marcomiranda"},
  {username: "amariellington"}
])

countries = Country.create([
  {name: "Belgium"},
  {name: "England"},
  {name: "Mexico"},
  {name: "United States of America"},
  {name: "Germany"},
  {name: "Czech Republic"},
  {name: "Brazil"},
  {name: "Italy"},
  {name: "Portugal"},
  {name: "Spain"},
  {name: "Scotland"},
  {name: "Denmark"},
  {name: "France"},
  {name: "Poland"},
  {name: "Netherland"},
  {name: "Ireland"}
])

beers = Beer.create([
  {name:"Corona Extra",
  brewery: "Cerveceria Modelo",
  country_id: 3,
  notes: "Born in Mexico and brought up on the beach, Corona is the perfect compliment to life’s simple pleasures. The golden colour, light refreshing flavor and iconic hand painted bottle, topped off with a freshly squeezed lime. When the living is easy, the beer is Corona.",
  abv: 4.5,
  image: "https://www.trzcacak.rs/file/max/2/26509_corona-png.png"},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  {name:"",
  brewery: "",
  country_id: ,
  notes: "",
  abv: ,
  image: ""},
  
])


